In [2]:
#Importar las librerias que vamos a usar 
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
#importamos el dataframe 
data=pd.read_csv("nissan-dataset.csv")
data

,id,full_name,age,gender,model,color,performance,km,condition,price
0,1,Dominic Applin,42.0,Male,Quest,Mauv,299.0,509305.0,very bad,40394.91
1,2,Lenee Eteen,54.0,Polygender,R'nessa,Orange,109.0,965853.0,old,8687.90
2,3,Kendal Esselin,37.0,Male,March / Micra,Teal,52.0,380906.0,bad,44705.31
3,4,Nehemiah Marvelley,55.0,Male,Gloria,Green,336.0,573171.0,very good,32889.88
4,5,Domenic McGeouch,21.0,Male,Avenir,Khaki,2.0,809470.0,old,6949.22
...,...,...,...,...,...,...,...,...,...,...
9995,9996,Mike Wilson,63.0,Polygender,Juke,Yellow,339.0,715741.0,new,19710.18
9996,9997,Katie Wilson,45.0,Female,Maxima,Gray,81.0,786768.0,bad,47797.76
9997,9998,Jane Davis,27.0,Female,Leaf,Yellow,130.0,99170.0,very bad,35058.91
9998,9999,Katie Smith,68.0,Male,March / Micra,Green,215.0,640764.0,old,21176.71
9999,10000,Katie Smith,69.0,Male,March / Micra,Green,215.0,640764.0,old,21177.71

In [ ]:
#Mi fuente ha sido integramente la web www.kaggle.com